<?php

namespace Model;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Src\Auth\IdentityInterface;

class User extends Model implements IdentityInterface {

    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'name',
        'login',
        'password'
    ];

    protected static function booted()
    {
        static::created(function ($user) {
            $user -> password = md5($user -> passworld);
            $user -> save();
        }); // TODO: Change the autogenerated stub
    }

    //Выборка пользователя по первичному ключу
    public function findIdentity(int $id)
    {
        // TODO: Implement findIdentity() method.
        return self::where('id', $id) -> first();
    }

    //Возврат первичного ключа
    public function getId(): int
    {
        // TODO: Implement getId() method.
        return $this -> id;
    }

    //Возврат аутентифицированного пользователя
    public function attemptIdentity(array $credentials)
    {
        // TODO: Implement attemptIdentity() method.
        return self::where(['login' => $credentials ['login'], 'password' => md5($credentials['password'])]) -> first();
    }

}